#!/bin/bash

if [ ! -h .gopath/src/github.com/aidora/prakob ]; then

	mkdir -p .gopath/src/github.com/aidora

	if [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
		junction .gopath/src/github.com/aidora/prakob `pwd -W` > /dev/null
	else
		ln -s ../../../../ .gopath/src/github.com/aidora/prakob
	fi

fi

if [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
	export GOBIN=`pwd -W`/bin
	export GOPATH=`pwd -W`/.gopath
else
	export GOBIN=$PWD/bin
	export GOPATH=$PWD/.gopath
fi

go install github.com/aidora/prakob